baseURL = 'https://blog.maxries.de'
languageCode = 'de-DE'
title = 'Fraktal Komplex'
theme = 'ink-free'
refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = 'https:/maxries.github.io/404'
[params]
	wpm = 250
[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderer]
  unsafe = true
